language: cpp
compiler: gcc
sudo: required
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-5 clang-3.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - ls -la /usr/bin | grep clang
  - sudo unlink /usr/bin/clang++
  - sudo ln -s /usr/bin/clang++-3.8 /usr/bin/clang++
  - which clang++
  - ls -la /usr/bin | grep clang
  #- sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 60 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-3.8
  - curl -O https://cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz
  - tar xfz cmake-3.5.1-Linux-x86_64.tar.gz
  - sudo unlink /usr/bin/cmake
  - sudo ln -s $TRAVIS_BUILD_DIR/cmake-3.5.1-Linux-x86_64/bin/cmake /usr/bin/cmake
  - curl -O http://valgrind.org/downloads/valgrind-3.11.0.tar.bz2
  - tar xjf valgrind-3.11.0.tar.bz2
  - cd valgrind-3.11.0
  - ./configure
  - make -j6
  - sudo make install
  - cd ..
script: ./generate_results.bash
os: linux
